export const blockReward = {
  "BTC": {
    dailyReward: 0.0004,
    timePerBlock: 600,
    name: "Bitcoin",
    ticker: "BTC",
    icon: "https://fatihcelikofficialtr.github.io/sayfa/fctest/img/btc.svg",
    coinGeckoId: "bitcoin",
  },
  "DOGE": {
    dailyReward: 140,
    timePerBlock: 600,
    name: "Dogecoin",
    ticker: "DOGE",
    icon: "https://fatihcelikofficialtr.github.io/sayfa/fctest/img/doge.svg",
    coinGeckoId: "dogecoin",
  },
  "ETH": {
    dailyReward: 0.007,
    timePerBlock: 600,
    name: "Ethereum",
    ticker: "ETH",
    icon: "https://fatihcelikofficialtr.github.io/sayfa/fctest/img/eth.svg",
    coinGeckoId: "ethereum",
  },
  "BNB": {
    dailyReward: 0.044,
    timePerBlock: 600,
    name: "Binancecoin",
    ticker: "BNB",
    icon: "https://fatihcelikofficialtr.github.io/sayfa/fctest/img/bnb.svg",
    coinGeckoId: "binancecoin",
  },
  "MATIC": {
    dailyReward: 5.5,
    timePerBlock: 600,
    name: "Polygon",
    ticker: "matic-network",
    icon: "https://fatihcelikofficialtr.github.io/sayfa/fctest/img/matic.svg",
    coinGeckoId: "matic-network",
  },
  "RLT": {
    dailyReward: 20,
    timePerBlock: 600,
    name: "Rollertoken",
    ticker: "RLT",
    icon: "https://fatihcelikofficialtr.github.io/sayfa/fctest/img/rlt.svg",
  },
  "SOL": {
    dailyReward: 0.23,
    timePerBlock: 600,
    name: "Solana",
    ticker: "SOL",
    icon: "https://fatihcelikofficialtr.github.io/sayfa/fctest/img/sol.svg",
    coinGeckoId: "solana",
  },
  "RST": {
    dailyReward: 150,
    timePerBlock: 600,
    name: "Roller Season Token",
    icon: "https://fatihcelikofficialtr.github.io/sayfa/fctest/img/rst.svg",
  },
  "TRX": {
    dailyReward: 60,
    timePerBlock: 600,
    name: "Tron",
    ticker: "tron",
    icon: "https://fatihcelikofficialtr.github.io/sayfa/fctest/img/trx.svg",
    coinGeckoId: "tron",
  },
  "LTC": {
    dailyReward: 0.015,
    timePerBlock: 600,
    name: "Litecoin",
    ticker: "ltc",
    icon: "https://fatihcelikofficialtr.github.io/sayfa/fctest/img/ltc.svg",
    coinGeckoId: "litecoin",
  },
}
